### ISSUE TITLE
Mailer testing in Scala

### ISSUE THREAD

**Issue by mkbehbehani** [Rhinofly/play-mailer#11]
What would be the recommended way to test mails sent from the plugin?

**Comment by EECOLOR** [comment]
We use the javamail mock library.  Add the following dependency in your build:

    "org.jvnet.mock-javamail" % "mock-javamail" % "1.9" % "test"

Then you can use code similar to the following to check the emails that were sent:

``` scala
val mailbox = Mailbox.get("email@domain")
if (mailbox.size == 1) {
  val email = mailbox.get(0)
  // tests on email
}
```

The full example of the test that checks the content can be found here: https://github.com/Rhinofly/play-mailer/blob/master/src/test/scala/testUtils/FullMessage.scala

In order to simulate a faulty mailbox use this:

``` scala
mailbox.setError(true)
```

And to clear the mailbox:

``` scala
mailbox.clear()
```

**Comment by mkbehbehani** [comment]
@EECOLOR Thank you! Your example worked perfectly.
